### ISSUE TITLE
License

### ISSUE THREAD

**Issue by NotSomething0** [Hills-Ground-City/HG-AntiCheat#1]
Hello, I see you're using and reuploading my code as your own which is fine albeit not cool. But under the GNU General Public License this source code needs to include the following.

- License and copyright notice
- State changes you've made to the source code
- Include the same license that is used in the original work

Although you're allowed to do whatever you'd like with this code I'd appreciate if you instead opened an issue and requested features be added instead.

Thanks,

NotSomething

**Comment by The-MG** [comment]
Hello @NotSomething0! 

I'm an admin for Hills Ground City, although I'm not sure what exactly this source is used for, I do know that we are trying to customize it to our needs rather than waiting for a developer to do it on your repository. I completely understand where you are coming from on the licensing, and copyright stuff though. I will have our developer look at this as soon as possible! 

Thanks,
Admin Team.

**Comment by knifeworm** [comment]
Hello @NotSomething0!

Thanks for posting this and having further review at yours and mines repository I do see what you mean.

I am reusing a anticheat that i made 2 or 3 years ago.

If you would like i can make a change to this anticheat so it does not look like yours.

Or i can add the licence and things that you would like added to to the repo.

Thanks
ILikeFivem > Project Manager

**Comment by knifeworm** [comment]
Hello @NotSomething0!

We have removed the files that were the same as your AntiCheat and will begin rewriting our AntiCheat today.

I hope this has solved your issue with the copyright and license complaint.

**Comment by NotSomething0** [comment]
Hey man like I said you're welcome to use my Anti-cheat and edit it to your liking so long as you abide by the license. None the less I appreciate your cooperation, if you would like to see features added to my Anti-cheat in the future don't hesitate to ask I love helping people.

Best of luck,

NotSomething
